// <auto-generated />
using System;
using EcommerceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceApp.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231101113151_initialSeed")]
    partial class initialSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoUrl = "https://static.vecteezy.com/system/resources/previews/010/994/412/non_2x/nike-logo-black-with-name-clothes-design-icon-abstract-football-illustration-with-white-background-free-vector.jpg",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            LogoUrl = "https://galleriaburgas.bg/?go=_common&p=companylogo&type=big&companyId=166",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            LogoUrl = "https://modista.bg/image/catalog/aaaaaaaaa%20loga/PUMA-logo.jpg",
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 4,
                            LogoUrl = "https://img.guess.com/image/upload/q_auto/v1/NA/Asset/North%20America/E-Commerce/Shared/Guess-196x196.png",
                            Name = "Guess"
                        },
                        new
                        {
                            Id = 5,
                            LogoUrl = "https://img.freepik.com/premium-vector/tommy-hilfiger-logo-set-top-clothing-brand-editorial-logotype-zdolbuniv-ukraine-april-26-2023_505956-735.jpg?w=2000",
                            Name = "Tommy Hilfiger"
                        },
                        new
                        {
                            Id = 6,
                            LogoUrl = "https://www.logo-designer.co/storage/2022/08/2022-hugo-boss-new-logo-design.png",
                            Name = "HUGO BOSS"
                        },
                        new
                        {
                            Id = 7,
                            LogoUrl = "https://i.pinimg.com/736x/6d/2c/cd/6d2ccd795e409bb68eec5db364e797ef.jpg",
                            Name = "Zara"
                        });
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Clothes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.MainCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MainCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jackets"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coats"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Trousers"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Skirts"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shorts"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Shirts"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sweatshirts"
                        });
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ClothId")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShoesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClothId");

                    b.HasIndex("ShoesId");

                    b.ToTable("Picture");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/b3546974-0d23-4657-a8a7-8d6abc9fc5e8/air-force-1-07-lv8-shoes-p2p25V.png",
                            ShoesId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0bab9b0c-3598-4b1f-b3eb-acd64788a258/air-force-1-07-lv8-shoes-p2p25V.png",
                            ShoesId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/67701610-e9ef-4dbf-9a3b-df35affa59cb/air-force-1-07-lv8-shoes-p2p25V.png",
                            ShoesId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9fec2c65-bf79-49ae-b6fa-158e74827be2/air-force-1-07-lv8-shoes-p2p25V.png",
                            ShoesId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/c599987c-9750-459a-badf-35805b4571e7/mercurial-vapor-15-pro-football-boot-4R8klC.png",
                            ShoesId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/576f6b39-4803-42ec-84f8-b57d2da31093/mercurial-vapor-15-pro-football-boot-4R8klC.png",
                            ShoesId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5e5eb7a2-59e5-44d7-bcde-e7389c729991/mercurial-vapor-15-pro-football-boot-4R8klC.png",
                            ShoesId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9d2426ad-828b-45f1-888e-7ea3af347b20/mercurial-vapor-15-pro-football-boot-4R8klC.png",
                            ShoesId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ecba7aa5-adf6-4a1d-855e-58df68fb9170/mercurial-superfly-9-elite-football-boot-D6qDRk.png",
                            ShoesId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/1e8ec3dd-4463-4e20-a5b1-f25c15869887/mercurial-superfly-9-elite-football-boot-D6qDRk.png",
                            ShoesId = 3
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/285cb55e-8273-459c-a261-dfd4a2c29ac8/mercurial-superfly-9-elite-football-boot-D6qDRk.png",
                            ShoesId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/0eba4f6d-54d3-4411-9343-f6f8fcdcf048/mercurial-superfly-9-elite-football-boot-D6qDRk.png",
                            ShoesId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/44103b50-8fd8-4316-91c9-526a794ed12f/air-max-tw-shoes-bfGWNc.png",
                            ShoesId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/5638aa3c-36da-438f-a41c-7cbd9ec9dce1/air-max-tw-shoes-bfGWNc.png",
                            ShoesId = 4
                        },
                        new
                        {
                            Id = 15,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/9265edc0-eb2e-40de-a224-1da42557b371/air-max-tw-shoes-bfGWNc.png",
                            ShoesId = 4
                        },
                        new
                        {
                            Id = 16,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3a59615f-7032-4c60-8848-5267fcdba4b6/air-max-tw-shoes-bfGWNc.png",
                            ShoesId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/efc9de26-5f37-4a37-a49b-3bf8639076d0/air-max-scorpion-flyknit-shoes-jhBW7t.png",
                            ShoesId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/e6ef5f97-e01d-4e3c-b929-e7f95a566f44/air-max-scorpion-flyknit-shoes-jhBW7t.png",
                            ShoesId = 5
                        },
                        new
                        {
                            Id = 19,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/3c93e6be-3b5f-4336-af41-da346f127403/air-max-scorpion-flyknit-shoes-jhBW7t.png",
                            ShoesId = 5
                        },
                        new
                        {
                            Id = 20,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d788cb32-f0e4-4426-acdf-f25b4ad3d574/air-max-scorpion-flyknit-shoes-jhBW7t.png",
                            ShoesId = 5
                        },
                        new
                        {
                            Id = 21,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/yommy4ijgwgrzbebxtvm/air-vapormax-plus-shoes-yATY9p7E.png",
                            ShoesId = 6
                        },
                        new
                        {
                            Id = 22,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/ehxtdksphjfm10zn2goz/air-vapormax-plus-shoes-yATY9p7E.png",
                            ShoesId = 6
                        },
                        new
                        {
                            Id = 23,
                            ImgUrl = "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/bv4nc2mve7pvlkhzzh9s/air-vapormax-plus-shoes-yATY9p7E.png",
                            ShoesId = 6
                        },
                        new
                        {
                            Id = 24,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20675.jpg",
                            ShoesId = 7
                        },
                        new
                        {
                            Id = 25,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20675_2.jpg",
                            ShoesId = 7
                        },
                        new
                        {
                            Id = 26,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20675_4.jpg",
                            ShoesId = 7
                        },
                        new
                        {
                            Id = 27,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20675_5.jpg",
                            ShoesId = 7
                        },
                        new
                        {
                            Id = 28,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20673.jpg",
                            ShoesId = 8
                        },
                        new
                        {
                            Id = 29,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20673_2.jpg",
                            ShoesId = 8
                        },
                        new
                        {
                            Id = 30,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20673_4.jpg",
                            ShoesId = 8
                        },
                        new
                        {
                            Id = 31,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Alphabounce%20Beyond%20Team%20-%20BG-%20673_5.jpg",
                            ShoesId = 8
                        },
                        new
                        {
                            Id = 32,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20ACE%2017%203%20Firm%20Ground%20-%20BG-O96%203371_1.jpg",
                            ShoesId = 9
                        },
                        new
                        {
                            Id = 33,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20ACE%2017%203%20Firm%20Ground%20-%20BG-O96%203371_2.jpg",
                            ShoesId = 9
                        },
                        new
                        {
                            Id = 34,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20ACE%2017%203%20Firm%20Ground%20-%20BG-O96%203371.jpg",
                            ShoesId = 9
                        },
                        new
                        {
                            Id = 35,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20ACE%2017%203%20Firm%20Ground%20-%20BG-O96%203371_3.jpg",
                            ShoesId = 9
                        },
                        new
                        {
                            Id = 36,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Adizero%208%200%20-%20BG-L307B%20521.jpg",
                            ShoesId = 10
                        },
                        new
                        {
                            Id = 37,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Adizero%208%200%20-%20BG-L307B%20521_2.jpg",
                            ShoesId = 10
                        },
                        new
                        {
                            Id = 38,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Adizero%208%200%20-%20BG-L307B%20521_3.jpg",
                            ShoesId = 10
                        },
                        new
                        {
                            Id = 39,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Adizero%208%200%20-%20BG-L307B%20521_5.jpg",
                            ShoesId = 10
                        },
                        new
                        {
                            Id = 40,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Predator%2019%203%20Laceless%20Firm%20G%201115.jpg",
                            ShoesId = 11
                        },
                        new
                        {
                            Id = 41,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Predator%2019%203%20Laceless%20Firm%20G%201115_2.jpg",
                            ShoesId = 11
                        },
                        new
                        {
                            Id = 42,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Predator%2019%203%20Laceless%20Firm%20G%201115_3.jpg",
                            ShoesId = 11
                        },
                        new
                        {
                            Id = 43,
                            ImgUrl = "https://www.sambabulgariashop.me/images/adidasbulgaria/Adidas%20Predator%2019%203%20Laceless%20Firm%20G%201115_4.jpg",
                            ShoesId = 11
                        },
                        new
                        {
                            Id = 44,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1350,h_1350/global/392434/02/sv01/fnd/EEA/fmt/png/Slipstream-Xtreme-Sneakers",
                            ShoesId = 12
                        },
                        new
                        {
                            Id = 45,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/392434/02/bv/fnd/EEA/fmt/png/Slipstream-Xtreme-Sneakers",
                            ShoesId = 12
                        },
                        new
                        {
                            Id = 46,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/392434/02/sv02/fnd/EEA/fmt/png/Slipstream-Xtreme-Sneakers",
                            ShoesId = 12
                        },
                        new
                        {
                            Id = 47,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/392434/02/sv04/fnd/EEA/fmt/png/Slipstream-Xtreme-Sneakers",
                            ShoesId = 12
                        },
                        new
                        {
                            Id = 48,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1350,h_1350/global/387544/02/sv01/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 13
                        },
                        new
                        {
                            Id = 49,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/387544/02/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 13
                        },
                        new
                        {
                            Id = 50,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/387544/02/bv/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 13
                        },
                        new
                        {
                            Id = 51,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/387544/02/sv02/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 13
                        },
                        new
                        {
                            Id = 52,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1350,h_1350/global/387544/16/sv01/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 14
                        },
                        new
                        {
                            Id = 53,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/387544/16/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 14
                        },
                        new
                        {
                            Id = 54,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/387544/16/bv/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 14
                        },
                        new
                        {
                            Id = 55,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/387544/16/sv04/fnd/EEA/fmt/png/Slipstream-Leather-Sneakers",
                            ShoesId = 14
                        },
                        new
                        {
                            Id = 56,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1350,h_1350/global/107214/03/sv01/fnd/EEA/fmt/png/ULTRA-ULTIMATE-MG-Football-Cleats-Men",
                            ShoesId = 15
                        },
                        new
                        {
                            Id = 57,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/107214/03/bv/fnd/EEA/fmt/png/ULTRA-ULTIMATE-MG-Football-Cleats-Men",
                            ShoesId = 15
                        },
                        new
                        {
                            Id = 58,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/107214/03/sv02/fnd/EEA/fmt/png/ULTRA-ULTIMATE-MG-Football-Cleats-Men",
                            ShoesId = 15
                        },
                        new
                        {
                            Id = 59,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/107214/03/sv04/fnd/EEA/fmt/png/ULTRA-ULTIMATE-MG-Football-Cleats-Men",
                            ShoesId = 15
                        },
                        new
                        {
                            Id = 60,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1350,h_1350/global/107535/03/sv01/fnd/EEA/fmt/png/ULTRA-PLAY-IT-Youth-Football-Boots",
                            ShoesId = 16
                        },
                        new
                        {
                            Id = 61,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/107535/03/sv02/fnd/EEA/fmt/png/ULTRA-PLAY-IT-Youth-Football-Boots",
                            ShoesId = 16
                        },
                        new
                        {
                            Id = 62,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/107535/03/sv02/fnd/EEA/fmt/png/ULTRA-PLAY-IT-Youth-Football-Boots",
                            ShoesId = 16
                        },
                        new
                        {
                            Id = 63,
                            ImgUrl = "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/107535/03/sv04/fnd/EEA/fmt/png/ULTRA-PLAY-IT-Youth-Football-Boots",
                            ShoesId = 16
                        });
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Shoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 9,
                            Color = "Black",
                            Description = "The radiance lives on in the Nike Air Force 1 '07 LV8. Crossing hardwood comfort with off-court flair, these kicks put a fresh spin on a hoops classic. Soft suede overlays pair with era-echoing '80s construction and reflective-design Swoosh logos to bring you nothing-but-net style while hidden full-length Air units add the legendary comfort you know and love.",
                            Gender = "Men",
                            Name = "Nike Air Force 1 '07 LV8",
                            Price = 130m,
                            StarRating = 5,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 9,
                            Color = "White",
                            Description = "The pitch is yours when you lace up in the Vapor 15 Pro AG-Pro. It's loaded with a Zoom Air unit, so you can dominate in the waning minutes of a match—when it matters most. Fast is in the Air.",
                            Gender = "Men",
                            Name = "Nike Mercurial Vapor 15 Pro",
                            Price = 160m,
                            StarRating = 5,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 9,
                            Color = "Black",
                            Description = "Instantly tilt the pitch in the bold design of the Superfly 9 Elite SG-Pro. We added a Zoom Air unit, made specifically for football, and grippy texture up top for exceptional touch, so you can dominate in the waning minutes of a match—when it matters most. Feel the explosive speed as you race around the pitch, making the critical plays with velocity and pace. Fast is in the Air. This version has Anti-Clog Traction on the soleplate, which helps prevent mud from sticking.",
                            Gender = "Men",
                            Name = "Nike Mercurial Superfly 9 Elite",
                            Price = 250m,
                            StarRating = 5,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 9,
                            Color = "Black",
                            Description = "So you're in love with the classic look of the '90s, but you've got a thing for today's fast-paced culture. Meet the Air Max TW. Inspired by the treasured franchise that brought Nike Air cushioning to the world and laid the foundation for the track-to-street aesthetic, its eye-catching design delivers a 1–2 punch of comfort and fashion. Ready to highlight any 'fit, its lightweight upper pairs angular and organic lines to create an entrancing haptic effect. The contrasting colourways make it easy to style. And if you're ready for the next step, the 5 windows underfoot deliver a modern edge to visible Air cushioning.",
                            Gender = "Men",
                            Name = "Nike Air Max TW",
                            Price = 0m,
                            StarRating = 5,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 9,
                            Color = "Black",
                            Description = "We looked into the future and it's gonna be comfy. Featuring a \"point-loaded\" Air unit (cushioning that forms to your every step), the Air Max Scorpion Flyknit delivers a futuristic sensation. And because looks count, we've crafted the upper from incredibly soft chenille-like fabric.",
                            Gender = "Women",
                            Name = "Nike Air Max Scorpion Flyknit",
                            Price = 160m,
                            StarRating = 5,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CategoryId = 9,
                            Color = "Blue",
                            Description = "The Nike Air VaporMax Plus looks to the past and propels you into the future. Nodding to the 1998 Air Max Plus with its floating cage, padded upper and heel logo, it adds revolutionary VaporMax Air technology to ramp up the comfort and create a modern look.",
                            Gender = "Men",
                            Name = "Nike Air VaporMax Plus",
                            Price = 180m,
                            StarRating = 5,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 9,
                            Color = "Dark Blue",
                            Description = "Designed for athletes who run to stay fit for their sport, these running shoes support multidirectional movements with flexible cushioning and a wide, stable platform in the forefoot and heel. They have a seamless, sock-like mesh upper with targeted areas of support and stretch for an adaptive fit.\r\nRunner type\r\nNeutral shoes for the versatile runner\r\nAdaptive fit\r\nSeamless Forgedmesh upper designed with areas of support and stretch to help ensure a custom fit that adapts to every move\r\nSpringy cushioning\r\nBounce cushioning provides enhanced comfort and flexibility\r\nReliable traction\r\nContinental™ Rubber outsole for extraordinary traction in wet and dry conditions",
                            Gender = "Men",
                            Name = "Adidas Alphabounce Beyond Team",
                            Price = 70m,
                            StarRating = 4,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            CategoryId = 9,
                            Color = "Dark Red",
                            Description = "Designed for athletes who run to stay fit for their sport, these running shoes support multidirectional movements with flexible cushioning and a wide, stable platform in the forefoot and heel. They have a seamless, sock-like mesh upper with targeted areas of support and stretch for an adaptive fit.\r\nRunner type\r\nNeutral shoes for the versatile runner\r\nAdaptive fit\r\nSeamless Forgedmesh upper designed with areas of support and stretch to help ensure a custom fit that adapts to every move\r\nSpringy cushioning\r\nBounce cushioning provides enhanced comfort and flexibility\r\nReliable traction\r\nContinental™ Rubber outsole for extraordinary traction in wet and dry conditions",
                            Gender = "Men",
                            Name = "Adidas Alphabounce Beyond Team",
                            Price = 70m,
                            StarRating = 4,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 9,
                            Color = "Orange",
                            Description = "Dominate space. Command the play. Create goal-destined shots from impossible angles. Control the game with every touch in ACE. These juniors' soccer cleats have a 3D Control Skin upper that delivers precise control with zero wear-in time. Designed to dominate on firm ground.",
                            Gender = "Men",
                            Name = "Adidas ACE 17.3 Firm Ground",
                            Price = 78.41m,
                            StarRating = 0,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            CategoryId = 9,
                            Color = "White",
                            Description = "Showcase your playmaking speed in these football cleats. Designed for easy on and off, they feature a textile upper with a sock-like construction for lightweight stability and lockdown as you create havoc at the line of scrimmage. The cleated outsole provides traction for quick cuts and pivots.. These juniors' soccer cleats have a 3D Control Skin upper that delivers precise control with zero wear-in time. Designed to dominate on firm ground.",
                            Gender = "Men",
                            Name = "Adidas Adizero 8.0",
                            Price = 83.41m,
                            StarRating = 0,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            CategoryId = 9,
                            Color = "Red",
                            Description = "If your command of the field leaves your rivals' tactics in tatters, you're ready to own Predators. Built for precision on firm ground, these soccer cleats have a supportive mesh upper that wraps around your foot to lock you in. This eliminates the need for laces and leaves more room for ball control. Embossing on the surface adds confidence to every touch.",
                            Gender = "Men",
                            Name = "Adidas Predator 19.3 Laceless Firm Ground",
                            Price = 83.41m,
                            StarRating = 0,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            CategoryId = 9,
                            Color = "Black",
                            Description = "We’re taking Slipstream to the extreme. This disruptive new version features an iconic Slipstream leather upper with elevated details, and a edgier sole with exaggerated proportions and rugged details. This execution features a leather base with nubuck overlays, a suede Formstrip with deep debossed lines and suede details.",
                            Gender = "Men",
                            Name = "Slipstream Xtreme Sneakers",
                            Price = 140m,
                            StarRating = 0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            CategoryId = 9,
                            Color = "White",
                            Description = "Back in 1987, the PUMA Slipstream Mid entered the scene as a basketball sneaker. A high-flying, slam-dunking, statement-making basketball sneaker. Now, it’s joined by the Slipstream – a rework of the original that brings an all-new energy to the game while staying true to the OG’s sporting roots.",
                            Gender = "Women",
                            Name = "Slipstream Leather Sneakers",
                            Price = 70m,
                            StarRating = 0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            CategoryId = 9,
                            Color = "Red",
                            Description = "Back in 1987, the PUMA Slipstream Mid entered the scene as a basketball sneaker. A high-flying, slam-dunking, statement-making basketball sneaker. Now, it’s joined by the Slipstream – a rework of the original that brings an all-new energy to the game while staying true to the OG’s sporting roots.",
                            Gender = "Women",
                            Name = "Slipstream Leather Sneakers",
                            Price = 70m,
                            StarRating = 0,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 3,
                            CategoryId = 9,
                            Color = "Green",
                            Description = "ULTRA - Not even you knew you could be this fast. Turn seconds into records with the ULTRA ULTIMATE football boot. Lighter means quicker, so the ULTRAWEAVE upper material makes every gram and every second count. Ultra-light. Ultra-fast. ULTRA ULTIMATE.",
                            Gender = "Men",
                            Name = "ULTRA ULTIMATE MG Football Cleats Men",
                            Price = 70m,
                            StarRating = 0,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 3,
                            CategoryId = 9,
                            Color = "Blue",
                            Description = "ULTRA - Not even you knew you could be this fast. Turn seconds into records with the ULTRA ULTIMATE football boot. Lighter means quicker, so the ULTRAWEAVE upper material makes every gram and every second count. Ultra-light. Ultra-fast. ULTRA ULTIMATE.",
                            Gender = "Men",
                            Name = "ULTRA PLAY IT Youth Football Boots",
                            Price = 60m,
                            StarRating = 0,
                            SubCategoryId = 4
                        });
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MainCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MainCategoryId");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MainCategoryId = 9,
                            Name = "Sports Shoes"
                        },
                        new
                        {
                            Id = 2,
                            MainCategoryId = 9,
                            Name = "Sandals"
                        },
                        new
                        {
                            Id = 3,
                            MainCategoryId = 9,
                            Name = "Trainers"
                        },
                        new
                        {
                            Id = 4,
                            MainCategoryId = 9,
                            Name = "Football Boats"
                        },
                        new
                        {
                            Id = 5,
                            MainCategoryId = 8,
                            Name = "Football Shirts"
                        },
                        new
                        {
                            Id = 6,
                            MainCategoryId = 8,
                            Name = "Long sleeve shirts"
                        },
                        new
                        {
                            Id = 7,
                            MainCategoryId = 8,
                            Name = "Short sleeve shirts"
                        },
                        new
                        {
                            Id = 8,
                            MainCategoryId = 8,
                            Name = "Dress Shirts"
                        },
                        new
                        {
                            Id = 9,
                            MainCategoryId = 7,
                            Name = "Swimming Shorts"
                        },
                        new
                        {
                            Id = 10,
                            MainCategoryId = 7,
                            Name = "Football Shorts"
                        },
                        new
                        {
                            Id = 11,
                            MainCategoryId = 7,
                            Name = "Cargo Shorts"
                        },
                        new
                        {
                            Id = 12,
                            MainCategoryId = 7,
                            Name = "Bermuda Shorts"
                        },
                        new
                        {
                            Id = 13,
                            MainCategoryId = 6,
                            Name = "Line Skirts"
                        },
                        new
                        {
                            Id = 14,
                            MainCategoryId = 6,
                            Name = "Tube Skirts"
                        },
                        new
                        {
                            Id = 15,
                            MainCategoryId = 6,
                            Name = "Cicle Skirts"
                        },
                        new
                        {
                            Id = 16,
                            MainCategoryId = 4,
                            Name = "Wrap Coats"
                        },
                        new
                        {
                            Id = 17,
                            MainCategoryId = 4,
                            Name = "Trench Coats"
                        },
                        new
                        {
                            Id = 18,
                            MainCategoryId = 4,
                            Name = "Fur Coats"
                        },
                        new
                        {
                            Id = 19,
                            MainCategoryId = 3,
                            Name = "Bomber Jackets"
                        },
                        new
                        {
                            Id = 20,
                            MainCategoryId = 3,
                            Name = "Denim Jackets"
                        },
                        new
                        {
                            Id = 21,
                            MainCategoryId = 3,
                            Name = "Biker Jackets"
                        },
                        new
                        {
                            Id = 22,
                            MainCategoryId = 2,
                            Name = "Straight leg jeans"
                        },
                        new
                        {
                            Id = 23,
                            MainCategoryId = 2,
                            Name = "Tapered jeans"
                        },
                        new
                        {
                            Id = 24,
                            MainCategoryId = 1,
                            Name = "Polo T-Shirts"
                        },
                        new
                        {
                            Id = 25,
                            MainCategoryId = 1,
                            Name = "Singlet T-shirts"
                        },
                        new
                        {
                            Id = 26,
                            MainCategoryId = 1,
                            Name = "Pocket T-shirts"
                        },
                        new
                        {
                            Id = 27,
                            MainCategoryId = 10,
                            Name = "Hooded Sweatshirts"
                        },
                        new
                        {
                            Id = 28,
                            MainCategoryId = 10,
                            Name = "Sweatshirts without a hood"
                        });
                });

            modelBuilder.Entity("EcommerceApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Clothes", b =>
                {
                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.Brand", "Brand")
                        .WithMany("Clothes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.MainCategory", "Category")
                        .WithMany("Clothes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.SubCategory", "SubCategory")
                        .WithMany("Clothes")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Picture", b =>
                {
                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.Clothes", "Cloth")
                        .WithMany()
                        .HasForeignKey("ClothId");

                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.Shoes", "Shoes")
                        .WithMany("Pictures")
                        .HasForeignKey("ShoesId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cloth");

                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Shoes", b =>
                {
                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.Brand", "Brand")
                        .WithMany("Shoes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.MainCategory", "Category")
                        .WithMany("Shoes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.SubCategory", "SubCategory")
                        .WithMany("Shoes")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.SubCategory", b =>
                {
                    b.HasOne("EcommerceApp.Infrastructure.Data.Models.MainCategory", "MainCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("MainCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MainCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EcommerceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EcommerceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EcommerceApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Brand", b =>
                {
                    b.Navigation("Clothes");

                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.MainCategory", b =>
                {
                    b.Navigation("Clothes");

                    b.Navigation("Shoes");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.Shoes", b =>
                {
                    b.Navigation("Pictures");
                });

            modelBuilder.Entity("EcommerceApp.Infrastructure.Data.Models.SubCategory", b =>
                {
                    b.Navigation("Clothes");

                    b.Navigation("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
